(function () {
  window.MobileGamesCatalog = [
    {
      name: "Snake Arena",
      nameZh: "贪吃蛇竞技场",
      path: "games/mobile/snake/web-mobile/",
      icon: "🐍",
      description: "A mobile-first snake battle with fast movement, bright effects, and quick arcade loops.",
      descriptionZh: "移动端优先的贪吃蛇竞技小游戏，节奏快、特效强，适合碎片时间开玩。",
      category: "Arcade",
      duration: "3-8 min",
      tags: ["mobile", "cocos", "arcade", "snake"],
      source: "mobile",
      platform: "mobile",
      featured: true,
      cover: "games/mobile/_covers/snake.jpg",
    },
    {
      name: "Tututu",
      nameZh: "突突突",
      path: "games/mobile/tututu/web-mobile/",
      icon: "🔫",
      description: "A light action shooter built for touch controls and instant replays.",
      descriptionZh: "偏轻量的动作射击小游戏，适合触屏操作和快速反复体验。",
      category: "Action",
      duration: "3-6 min",
      tags: ["mobile", "cocos", "shooter", "action"],
      source: "mobile",
      platform: "mobile",
      featured: true,
      cover: "games/mobile/_covers/tututu.png",
    },
    {
      name: "YSDH",
      nameZh: "勇士大横",
      path: "games/mobile/ysdh/web-mobile/",
      icon: "⚔️",
      description: "An action-heavy mobile game focused on quick combat and scene transitions.",
      descriptionZh: "强调战斗节奏和场景切换的移动端动作小游戏。",
      category: "Action",
      duration: "5-10 min",
      tags: ["mobile", "combat", "cocos", "action"],
      source: "mobile",
      platform: "mobile",
      featured: true,
      cover: "games/mobile/_covers/daheng.png",
    },
    {
      name: "Global Tycoon",
      nameZh: "环球大亨",
      path: "games/mobile/globalTycoon/web-mobile/",
      icon: "🌍",
      description: "A compact business sim with global expansion flavor and management choices.",
      descriptionZh: "带有全球扩张感的轻量经营模拟小游戏。",
      category: "Strategy",
      duration: "8-15 min",
      tags: ["mobile", "strategy", "management", "sim"],
      source: "mobile",
      platform: "mobile",
      featured: true,
      cover: "games/mobile/_covers/world.jpg",
    },
    {
      name: "Fight",
      nameZh: "格斗挑战",
      path: "games/mobile/fight/web-mobile/",
      icon: "🥊",
      description: "A direct touch-friendly fighting game with punchy effects and simple controls.",
      descriptionZh: "操作简单、反馈直接的触屏格斗小游戏。",
      category: "Action",
      duration: "3-6 min",
      tags: ["mobile", "fight", "action", "cocos"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/fight.jpg",
    },
    {
      name: "Daluosi",
      nameZh: "大螺丝",
      path: "games/mobile/daluosi/web-mobile/",
      icon: "🌹",
      description: "A themed casual game with short sessions and simple touch interactions.",
      descriptionZh: "主题感较强的休闲触控小游戏，玩法轻松，适合短局体验。",
      category: "Casual",
      duration: "2-5 min",
      tags: ["mobile", "casual", "touch", "cocos"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/rose.jpg",
    },
    {
      name: "Dancing",
      nameZh: "节奏舞动",
      path: "games/mobile/dancing/web-mobile/",
      icon: "🎵",
      description: "A rhythm-flavored mobile mini-game with fast timing feedback.",
      descriptionZh: "强调节奏和时机判断的移动端音乐小游戏。",
      category: "Music",
      duration: "2-4 min",
      tags: ["mobile", "music", "rhythm", "cocos"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/music.jpg",
    },
    {
      name: "Jieya",
      nameZh: "解压工坊",
      path: "games/mobile/jieya/web-mobile/",
      icon: "🫧",
      description: "A decompression-style casual game designed for quick taps and relaxing loops.",
      descriptionZh: "偏解压体验的休闲小游戏，点点按按就能获得轻松反馈。",
      category: "Casual",
      duration: "1-4 min",
      tags: ["mobile", "casual", "relax", "touch"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/jieya.jpg",
    },
    {
      name: "Mori Agent",
      nameZh: "末日特工",
      path: "games/mobile/moritegong/web-mobile/",
      icon: "🕶️",
      description: "A spy-style action game with bold visual identity and mobile pacing.",
      descriptionZh: "特工题材的动作小游戏，风格鲜明，适合移动端快节奏游玩。",
      category: "Action",
      duration: "4-7 min",
      tags: ["mobile", "agent", "action", "cocos"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/tegong.jpg",
    },
    {
      name: "Save Dog",
      nameZh: "救救小狗",
      path: "games/mobile/savedog/web-mobile/",
      icon: "🐶",
      description: "A viral puzzle style game built around protecting a dog from danger.",
      descriptionZh: "围绕“保护小狗”展开的热门休闲益智玩法。",
      category: "Puzzle",
      duration: "2-5 min",
      tags: ["mobile", "puzzle", "casual", "save-dog"],
      source: "mobile",
      platform: "mobile",
      featured: true,
      cover: "games/mobile/_covers/savedog.jpg",
    },
    {
      name: "DXCYXTGD",
      nameZh: "割草挑战",
      path: "games/mobile/dxcyxtgd/web-mobile/",
      icon: "🌿",
      description: "A satisfying field-clearing mini-game with obvious touch-first design.",
      descriptionZh: "明显面向触屏设计的割草题材小游戏，反馈直接，爽感明显。",
      category: "Action",
      duration: "3-6 min",
      tags: ["mobile", "action", "casual", "survival"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/gecao.jpg",
    },
    {
      name: "Toujinzi",
      nameZh: "投金子",
      path: "games/mobile/toujinzi/web-mobile/",
      icon: "🪙",
      description: "A casual toss-and-score game with strong arcade feedback.",
      descriptionZh: "主打投掷和得分反馈的轻量街机小游戏。",
      category: "Arcade",
      duration: "1-3 min",
      tags: ["mobile", "arcade", "casual", "score"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/jinzi.png",
    },
    {
      name: "Science 51",
      nameZh: "51 科学课堂",
      path: "games/mobile/51/web-mobile/",
      icon: "🧪",
      description: "An educational touch game blending simple mechanics with science-themed content.",
      descriptionZh: "把轻量玩法和科普内容结合在一起的教育向小游戏。",
      category: "Educational",
      duration: "3-6 min",
      tags: ["mobile", "education", "science", "touch"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/class.png",
    },
    {
      name: "Rocket Match",
      nameZh: "火箭消除",
      path: "games/mobile/rocket/web-mobile/",
      icon: "🚀",
      description: "A bright elimination game with easy onboarding and quick scoring loops.",
      descriptionZh: "色彩明快、上手简单的消除类小游戏。",
      category: "Puzzle",
      duration: "3-5 min",
      tags: ["mobile", "puzzle", "match", "casual"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/xiaoxiaole.jpg",
    },
    {
      name: "Lianlian Kan",
      nameZh: "连连看",
      path: "games/mobile/lianlain/",
      icon: "🀄",
      description: "A classic connect-and-clear puzzle game exported as a polished mobile web build.",
      descriptionZh: "经典连连看玩法，已经整理成完整的移动 H5 发布包。",
      category: "Puzzle",
      duration: "5-10 min",
      tags: ["mobile", "puzzle", "board", "connect"],
      source: "mobile",
      platform: "mobile",
      featured: true,
      cover: "games/mobile/_covers/lianlian.jpg",
    },
    {
      name: "Matchstick Gunner",
      nameZh: "火柴人枪手",
      path: "games/mobile/huocairen_gun/web-mobile/",
      icon: "🔫",
      description: "A stickman shooting game with straightforward mobile controls.",
      descriptionZh: "主打火柴人题材的移动端射击小游戏。",
      category: "Action",
      duration: "3-7 min",
      tags: ["mobile", "stickman", "shooter", "action"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/huocairen.jpg",
    },
    {
      name: "Save Chicken",
      nameZh: "拯救小鸡",
      path: "games/mobile/jiujiuxiaoji/web-mobile/",
      icon: "🐥",
      description: "A cute rescue game designed around quick reflexes and cheerful art.",
      descriptionZh: "画风轻快、围绕小鸡救援展开的休闲小游戏。",
      category: "Casual",
      duration: "2-5 min",
      tags: ["mobile", "casual", "cute", "reaction"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/chicken.jpg",
    },
    {
      name: "Giraffe Run",
      nameZh: "长颈鹿奔跑",
      path: "games/mobile/giraffe/web-mobile/",
      icon: "🦒",
      description: "A whimsical runner with playful art and simple mobile pacing.",
      descriptionZh: "风格轻松的动物跑酷小游戏，适合手机端快速体验。",
      category: "Arcade",
      duration: "2-4 min",
      tags: ["mobile", "runner", "animal", "arcade"],
      source: "mobile",
      platform: "mobile",
      cover: "games/mobile/_covers/giraffe.jpg",
    },
    {
      name: "Spring Word Race",
      nameZh: "春日单词冲刺",
      path: "games/mobile/SpringWordRace/",
      icon: "🌸",
      description: "A word-racing educational mini-game with cheerful mobile presentation.",
      descriptionZh: "把单词练习做成闯关竞速的教育向小游戏。",
      category: "Educational",
      duration: "3-8 min",
      tags: ["mobile", "word", "education", "cocos"],
      source: "mobile",
      platform: "mobile",
      featured: true,
    },
    {
      name: "Sheep Challenge",
      nameZh: "绵羊挑战",
      path: "games/mobile/sheep/",
      icon: "🐑",
      description: "A character-rich Cocos Creator game with audio, textures, and animation assets.",
      descriptionZh: "资源较完整、包含音频和动画素材的 Cocos Creator 移动小游戏。",
      category: "Casual",
      duration: "4-8 min",
      tags: ["mobile", "cocos", "casual", "animation"],
      source: "mobile",
      platform: "mobile",
    },
    {
      name: "Devil Escape",
      nameZh: "恶魔逃脱",
      path: "games/mobile/devil/web-mobile/",
      icon: "😈",
      description: "A fantasy-themed mobile mini-game with brisk action beats.",
      descriptionZh: "奇幻风格的动作向移动小游戏，节奏轻快。",
      category: "Action",
      duration: "3-6 min",
      tags: ["mobile", "fantasy", "action", "escape"],
      source: "mobile",
      platform: "mobile",
    },
    {
      name: "Flying Cards",
      nameZh: "飞牌挑战",
      path: "games/mobile/feipai/web-mobile/",
      icon: "🃏",
      description: "A precision-and-timing arcade game centered on card throws.",
      descriptionZh: "围绕飞牌操作做出的时机型街机小游戏。",
      category: "Arcade",
      duration: "1-4 min",
      tags: ["mobile", "arcade", "precision", "timing"],
      source: "mobile",
      platform: "mobile",
    },
    {
      name: "Fruit Splash",
      nameZh: "水果冲刺",
      path: "games/mobile/fruit/web-mobile/",
      icon: "🍉",
      description: "A fruit-themed casual game built for bright mobile sessions.",
      descriptionZh: "水果主题的休闲小游戏，画面明快，适合移动端轻松游玩。",
      category: "Casual",
      duration: "2-4 min",
      tags: ["mobile", "fruit", "casual", "touch"],
      source: "mobile",
      platform: "mobile",
    },
    {
      name: "Quick Hit",
      nameZh: "快速一击",
      path: "games/mobile/quickhit/web-mobile/",
      icon: "⚡",
      description: "A reflex-based arcade title centered on fast timing windows.",
      descriptionZh: "基于反应速度和点击时机的快节奏街机小游戏。",
      category: "Arcade",
      duration: "1-3 min",
      tags: ["mobile", "arcade", "reaction", "timing"],
      source: "mobile",
      platform: "mobile",
    },
    {
      name: "Sword Rush",
      nameZh: "刀剑冲锋",
      path: "games/mobile/sword/web-mobile/",
      icon: "🗡️",
      description: "A hack-and-dodge mobile action mini-game with simple controls.",
      descriptionZh: "强调砍击和闪避体验的轻量动作小游戏。",
      category: "Action",
      duration: "3-6 min",
      tags: ["mobile", "sword", "action", "combat"],
      source: "mobile",
      platform: "mobile",
    },
    {
      name: "Tank Battle",
      nameZh: "坦克大战",
      path: "games/mobile/tank/web-mobile/",
      icon: "🛡️",
      description: "A top-down tank game that translates classic arcade structure to touch screens.",
      descriptionZh: "把经典坦克大战节奏搬到移动端触屏体验上的小游戏。",
      category: "Arcade",
      duration: "3-8 min",
      tags: ["mobile", "tank", "arcade", "battle"],
      source: "mobile",
      platform: "mobile",
    },
    {
      name: "Weiqi",
      nameZh: "围棋入门",
      path: "games/mobile/weiqi/web-mobile/",
      icon: "⚫",
      description: "A board-game flavored mobile experience inspired by Go and strategy play.",
      descriptionZh: "带有围棋和棋盘策略气质的移动端小游戏。",
      category: "Board",
      duration: "8-15 min",
      tags: ["mobile", "board", "strategy", "weiqi"],
      source: "mobile",
      platform: "mobile",
    },
    {
      name: "Cloud Cart",
      nameZh: "云游车",
      path: "games/mobile/yunyouche/web-mobile/",
      icon: "🚗",
      description: "A driving-themed touch game built around motion and route control.",
      descriptionZh: "偏驾驶和路线操控体验的移动端小游戏。",
      category: "Arcade",
      duration: "2-6 min",
      tags: ["mobile", "driving", "arcade", "touch"],
      source: "mobile",
      platform: "mobile",
    },
  ];
})();
